// This file is auto-generated by Milk
// Do not edit manually.

export type TableMap = {
  "Example": {
    name: string
    active: boolean
    birthday: string
    count: number
    updatedAt: string
    createdAt: string
 };
  "Person": {
    name: string
    age: number
    birthday: string
 };
};
