import { getAllModels, getSchema } from "../core/modelRegistry";
import fs from "fs";
import path from "path";

export const generateTypes = async () => {
  const lines: string[] = [];
  lines.push(`// This file is auto-generated by Milk`);
  lines.push(`// Do not edit manually.\n`);
  lines.push("export type TableMap = {");

  const models = getAllModels();

  if (models.length === 0) {
    console.warn("🥛 [Milk] - No models found. Did you forget to use @Use()?");
  }

  for (const [, meta] of models) {
    const { tableName, instance } = meta;
    const schema = getSchema(instance);

    const fields = Object.entries(schema)
      .map(([key, col]) => {
        const tsType = sqlTypeToTs(col.type || "");
        return `    ${key}: ${tsType}`;
      })
      .join("\n");

    lines.push(`  "${tableName}": {\n${fields}\n };`);
  }

  lines.push("};\n");

  const outPath = path.resolve(process.cwd(), "milk.d.ts");
  fs.writeFileSync(outPath, lines.join("\n"), "utf-8");

  console.log("🥛 [Milk] - Generated milk.d.ts");
};

const sqlTypeToTs = (type: string): string => {
  const t = type.toLowerCase();
  if (t.includes("int")) return "number";
  if (t.includes("char") || t.includes("text")) return "string";
  if (t.includes("bool")) return "boolean";
  if (t.includes("date") || t.includes("time")) return "string";
  return "any";
};
