import { getAllModels, getSchema } from "../orm/schema/modelRegistry";
import fs from "fs";
import path from "path";
import type { Column } from "../orm";
import { log, warn } from "../utils/log";

export const generateTypes = async () => {
  const lines: string[] = [];
  lines.push(`// This file is auto-generated by Milk`);
  lines.push(`// Do not edit manually.\n`);
  lines.push("export type TableMap = {");

  const models = getAllModels();

  if (models.length === 0) {
    warn("No models found. Did you forget to use @Use()?");
  }

  for (const [, meta] of models) {
    const { tableName, instance } = meta;
    const schema = getSchema(instance);

    const fields = Object.entries(schema)
      .map(([key, col]) => {
        const tsType = sqlTypeToTs(col);
        return `    ${key}: ${tsType}`;
      })
      .join("\n");

    lines.push(`  "${tableName}": {\n${fields}\n };`);
  }

  lines.push("};\n");

  const outPath = path.resolve(process.cwd(), "milk.d.ts");
  fs.writeFileSync(outPath, lines.join("\n"), "utf-8");

  log("Generated milk.d.ts");
};

const sqlTypeToTs = (col: Column): string => {
  const colType = col.type?.toLowerCase() || "";
  const opts = col.options;

  if (opts.primary && opts.autoIncrement) return "number";
  if (opts.primary && opts.default === "uuid()") return "string";

  if (colType.includes("int")) return "number";
  if (colType.includes("char") || colType.includes("text")) return "string";
  if (colType.includes("bool")) return "boolean";
  if (colType.includes("date") || colType.includes("time")) return "string";

  return "any";
};
